[package]
name = "gnopi"
version = "0.1.0"
edition = "2021"
description = "A Ï€ memorization trainer"

[dependencies]
dirs = "5.0.1"
relm4 = { version = "0.8.0", features = ["libadwaita", "gnome_46"] }

[build-dependencies]
glib-build-tools = "0.19.0"
